// Generated by IcedCoffeeScript 108.0.11
(function() {
  app.controller("LayoutCtrl", [
    "$scope", "$interval", "$http", function($scope, $interval, $http) {
      var getNotification;
      $scope.appSettings = appSettings;
      $scope.appNotifications = [];
      getNotification = function() {
        return $http.get($scope.appSettings.appNotification.url).success(function(data) {
          return angular.forEach(data, function(item) {
            return $scope.appNotifications.push(item);
          });
        });
      };
      if ($scope.appSettings.appNotification.url) {
        getNotification();
        $interval(function() {
          return getNotification();
        }, $scope.appSettings.appNotification.interval * 60 * 1000);
      }
      $scope.appMenus = [];
      if ($scope.appSettings.appMenu.url) {
        $http.get($scope.appSettings.appMenu.url).success(function(data) {
          return $scope.appMenus = data;
        });
      }
      $scope.onNotificationClick = function(item) {
        $scope.appNotifications.splice($scope.appNotifications.indexOf(item), 1);
        return dialog.alert(item.title);
      };
      $scope.logout = function() {
        return dialog.confirm("Are you sure you want to log out?", function() {
          dialog.success("Logged out");
          return location.href = "/admin/account/logout";
        });
      };
    }
  ]);

}).call(this);
