// Generated by IcedCoffeeScript 108.0.11
(function() {
  app.controller("LayoutCtrl", [
    "$scope", "$interval", "$http", function($scope, $interval, $http) {
      $scope.appSettings = appSettings;
      if ($scope.appSettings.appNotification.url) {
        $interval(function() {
          return $http.get($scope.appSettings.appNotification.url, function(data) {
            return $scope.appSettings.appNotification.data = data;
          });
        }, $scope.appSettings.appNotification.interval * 60 * 1000);
      }
      if ($scope.appSettings.appMenu.url) {
        return $http.get($scope.appSettings.appMenu.url, function(data) {
          return $scope.appSettings.appMenu.data = data;
        });
      }
    }
  ]);

}).call(this);
