// Generated by IcedCoffeeScript 108.0.11
(function() {
  var app;

  app = angular.module("ngApp", ["ngSanitize", "bn.filters", "bn.ui.input", "bn.ui.select", "bn.ui.checks", "bn.ui.pager"]);

  window.app = app;

}).call(this);
