// Generated by IcedCoffeeScript 108.0.11
(function() {
  app.controller("LoginCtrl", [
    "$scope", "$http", function($scope, $http) {
      $scope.appSettings = appSettings;
    }
  ]);

}).call(this);
