// Generated by IcedCoffeeScript 108.0.11
(function() {
  app.controller("LoginCtrl", [
    "$scope", "$http", function($scope, $http) {
      $scope.appSettings = appSettings;
      $scope.model = {};
      $scope.login = function() {
        $scope.isLoading = true;
        dialog.loading(".panel-body");
        return $http.post("/admin/account/login", $scope.model).success(function(data) {
          console.debug(data);
          $scope.isLoading = false;
          return dialog.loaded(".panel-body");
        }).error(function(rep) {
          dialog.error("Failed to log in.", 5);
          return $scope.isLoading = false;
        });
      };
    }
  ]);

}).call(this);
