// Generated by IcedCoffeeScript 108.0.11
(function() {
  app.controller("FormCtrl", [
    "$scope", "$http", "FileUploader", function($scope, $http, FileUploader) {
      var uploader;
      $scope.model = {
        select: "2",
        radio: 1,
        checkbox: [1, 3]
      };
      $scope.options = {
        "Option 1": 1,
        "Option 2": 2,
        "Option 3": 3
      };
      uploader = $scope.uploader = new FileUploader({
        url: '/admin/file/upload'
      });
      uploader.filters.push({
        name: 'customFilter',
        fn: function(item, options) {
          return this.queue.length < 10;
        }
      });
      uploader.onWhenAddingFileFailed = function(item, filter, options) {
        return console.info('onWhenAddingFileFailed', item, filter, options);
      };
      uploader.onAfterAddingFile = function(fileItem) {
        return console.info('onAfterAddingFile', fileItem);
      };
      uploader.onAfterAddingAll = function(addedFileItems) {
        return console.info('onAfterAddingAll', addedFileItems);
      };
      uploader.onBeforeUploadItem = function(item) {
        return console.info('onBeforeUploadItem', item);
      };
      uploader.onProgressItem = function(fileItem, progress) {
        return console.info('onProgressItem', fileItem, progress);
      };
      uploader.onProgressAll = function(progress) {
        return console.info('onProgressAll', progress);
      };
      uploader.onSuccessItem = function(fileItem, response, status, headers) {
        return console.info('onSuccessItem', fileItem, response, status, headers);
      };
      uploader.onErrorItem = function(fileItem, response, status, headers) {
        return console.info('onErrorItem', fileItem, response, status, headers);
      };
      uploader.onCancelItem = function(fileItem, response, status, headers) {
        return console.info('onCancelItem', fileItem, response, status, headers);
      };
      uploader.onCompleteItem = function(fileItem, response, status, headers) {
        return console.info('onCompleteItem', fileItem, response, status, headers);
      };
      uploader.onCompleteAll = function() {
        return console.info('onCompleteAll');
      };
      console.info('uploader', uploader);
      $scope.submitForm = function() {
        if ($scope.form.$invalid) {
          dialog.error("Form is invalid");
        } else {
          return dialog.success(angular.toJson($scope.model));
        }
      };
    }
  ]);

}).call(this);
