// Generated by IcedCoffeeScript 108.0.11
(function() {
  app.controller("FormCtrl", [
    "$scope", "$http", function($scope, $http) {
      $scope.formModel = {};
      $scope.submitForm = function() {
        if ($scope.form.$invalid) {
          dialog.error("Form is invalid");
        } else {
          return dialog.success(angular.toJson($scope.formModel));
        }
      };
    }
  ]);

}).call(this);
