// Generated by IcedCoffeeScript 108.0.11
(function() {
  app.controller("TableCtrl", [
    "$scope", "$http", function($scope, $http) {
      $scope.search = function(p) {
        return $http.get("search?page=" + p + "&pagesize=10").success(function(d) {
          return $scope.model = d;
        });
      };
      $scope.search(1);
      return $scope.remove = function(item) {
        return dialog.confirm("Are you sure you want to remove this item?", function() {
          return $scope.$apply(function() {
            return $scope.model.data.splice($scope.model.data.indexOf(item), 1);
          });
        });
      };
    }
  ]);

}).call(this);
